name = "numi-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5013ce03fb3a4b17a96e1e152d568708" # สร้างด้วย: npx wrangler kv namespace create RATE_LIMIT
